### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

### ISSUE THREAD

**Issue by GueorguiK** [ShichaoJin/VCNN#1]
Hi !

I can't run this algo I got this : 

> File "/home/VCNN/scripts/vcnnmodel.py", line 167, in disc_loss
    rs_add = torch.norm(rs_center-6*conf['c0'],2,1,keepdim=True)   
  File "/home/anaconda3/lib/python3.7/site-packages/torch/functional.py", line 769, in norm
    return torch._C._VariableFunctions.norm(input, p, dim, keepdim=keepdim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

And btw for embed(), maybe delete these, there are useful only if we want to explore ?

Thx !

**Comment by GueorguiK** [comment]
Think it's linked to log_softmax function which has been deprecated, we have to specify the dimension ?

**Comment by mserouar** [comment]
Yes,  this is a custom loss function.
According to the script `rs_add = torch.norm(rs_center-6*conf['c0'],2,1)` must be replaced by `rs_add = torch.norm(rs_center-6*conf['c0'],2,0)`, I don't know if this is a mistake but `rs_center` format is like `tensor([4.2562, 6.2438, 5.7405, 6.6289, 6.3764, 6.3724, 5.2877])` ain't got more than 0 dim.

You'll have to change `epoch_loss += loss.data[0]` to `epoch_loss += loss.item()`, because of this 0-dim tensor youl'll have to convert these 0-dim tensors (and for conflicts with Torch v < 0.5), same as `epoch_cluster += part_loss.data[0]` to `epoch_cluster += part_loss.item()`


Everything is running, but still have a small problem, Accuracy and Dice, in training phase, are still 0%, while loss is decreasing correctly. I mean you just have to add `.item()` to `accuracy = pred.eq(true).cpu().sum()` 

#---

@ShichaoJin
We don't have any accuracy / F-score for multiclass segmentation ?

**Comment by GueorguiK** [comment]
Ok ok, Do you know how to modify to launch dataset test ?

**Comment by mserouar** [comment]
Yeah, in _get_test_data add `minxyz = min(gt_x)` and change `return (xyz, cls,cur_xyz,scale,minxyz,cur_xyz_o,cur_cls_label,cur_part_label)` to  `return (gt_x, gt_y,cur_xyz,scale,minxyz,cur_xyz_o,cur_cls,cur_part)`

And then from `for partial_epoch, (image, label,cur_xyz,scale,cur_xyz_o) in enumerate(training_data_loader(), 0):
` to `for partial_epoch, (image, label,cur_xyz,scale,minxyz,cur_xyz_o,cur_cls_label,cur_part_label) in enumerate(validation_data_loader(), 0): `

As you don’t want to train anymore. It isn’t optimal as you train and test on the same dataset, but feel free to delete some lines in the main h5 file or to simulate new ones.

I think the author may confirm if I’m right, he better knows his algo than me. Because I'm not pretty sure about it, this way of coding isn't familiar and some parts are written but never called, I don't know if I should deal with it or load the saved .pth model.
